######################################################################
# Automatically generated by qmake (2.01a) ?? 4? 6 14:15:33 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += xunlian.cpp
