######################################################################
# Automatically generated by qmake (2.01a) ?? 8? 17 16:42:15 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += xuzhi.h
SOURCES += main.cpp xuzhi.cpp
