######################################################################
# Automatically generated by qmake (2.01a) ?? 4? 7 14:49:36 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network

# Input
HEADERS += CImage_DaZhengGUO.h
SOURCES += CImage_DaZhengGUO.cpp main.cpp
