######################################################################
# Automatically generated by qmake (2.01a) ?? 4? 7 14:54:51 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network

# Input
HEADERS += CImage_TongHuaXI.h
SOURCES += CImage_TongHuaXI.cpp main.cpp
