######################################################################
# Automatically generated by qmake (2.01a) ?? 8? 16 15:06:51 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network

# Input
HEADERS += zijian.h
SOURCES += main.cpp zijian.cpp
