######################################################################
# Automatically generated by qmake (2.01a) ?? 4? 24 14:19:21 2017
######################################################################

TEMPLATE = app
TARGET =
DEPENDPATH += .
INCLUDEPATH += .
QT += network

# Input
HEADERS += dialog.h training.h
FORMS += dialog.ui training.ui
SOURCES += dialog.cpp main.cpp training.cpp
