######################################################################
# Automatically generated by qmake (2.01a) ?? 4? 7 10:53:35 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network

# Input
HEADERS += CImage.h
SOURCES += CImage.cpp main.cpp
