######################################################################
# Automatically generated by qmake (2.01a) ?? 8? 21 16:40:33 2017
######################################################################

TEMPLATE = app
TARGET =
DEPENDPATH += .
INCLUDEPATH += .
QT += network

# Input
HEADERS += bidui.h
SOURCES += bidui.cpp main.cpp
